### ISSUE TITLE
Default short arguments

### ISSUE THREAD

**Issue by anntzer** [evanunderscore/defopt#21]
It would be nice if keyword arguments which do not share their initial with any other keyword argument could automatically provide a short form, i.e.
```
def main(foo: str = "foo", bar: str = "bar"): ...
```
results in the options `-f`, `--foo`, `-b`, `--bar`.

**Comment by evanunderscore** [comment]
I like this idea. I didn't do it originally because I didn't want adding a parameter to be able to break backwards compatibility. For example, if you later come and add `baz`, you'll lose the `-b`. I think if we do this it should be opt-in. Also note that you already get the default argparse behavior of allowing unambiguous shortened flags, e.g. `--f` and `--fo`.

Would you like to work on a PR?

**Comment by anntzer** [comment]
I don't think(?) shortened long flags can be stacked as `--abc` (for `--a --b --c`).

This feature doesn't necessarily break backcompatibility as you can apparently just pass whatever short flags you want to `defopt.run` (although an example is actually missing at http://defopt.readthedocs.io/en/latest/examples.html#module-examples.short).  So if someone wants to add a second option with the same initial, they has the choice of whether to break backcompat, or just disambiguate things themselves.

No time for a PR *right now*...

**Comment by anntzer** [comment]
If you *really* want to play extra safe, you could issue a warning whenever multiple short flags conflict (with an option to disable it).  But *that* would break backcompatibility of defopt.

I don't think the backcompatibility issue on the user side is that big, even if the dev does no testing -- at worst, what happens is that someone was using a short flag, sees that it doesn't work anymore, complains to the dev, who realizes the issue and resolves it manually.  It's never going to run an incorrect command, at least.
